export { default as ImageAboutA1 } from './image-about-a-1.jpg';
export { default as ImageAboutA2 } from './image-about-a-2.jpg';
export { default as ImageAboutA3 } from './image-about-a-3.jpg';
export { default as ImageAboutGallery2 } from './image-about-gallery-2.jpg';
export { default as ImageAboutGallery3 } from './image-about-gallery-3.jpg';
export { default as ImageAboutGallery4 } from './image-about-gallery-4.jpg';
export { default as ImageAboutGallery5 } from './image-about-gallery-5.jpg';
export { default as ImageAboutWhoWeAre } from './image-about-who-we-are.jpg';
export { default as ImageLandingHero } from './image-landing-hero.jpg';
